# Generated by Django 3.0.5 on 2020-05-11 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_auto_20200511_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='created_at',
            new_name='date',
        ),
    ]
