# Generated by Django 3.0.5 on 2020-05-25 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
