# Generated by Django 3.0.5 on 2020-05-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20200525_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='expenses.Category'),
            preserve_default=False,
        ),
    ]
